name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ main, feature/lab3 ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run in'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Gather System Information
        run: |
          echo "=== SYSTEM INFORMATION REPORT ==="
          echo ""
          echo "--- Operating System ---"
          echo "OS: $(uname -s)"
          echo "Kernel: $(uname -r)"
          echo "Architecture: $(uname -m)"
          echo "Hostname: $(hostname)"
          echo ""
          echo "--- Hardware Specifications ---"
          echo "CPU Cores: $(nproc)"
          echo "CPU Model: $(grep -m 1 'model name' /proc/cpuinfo | cut -d: -f2 | xargs)"
          echo "Total Memory: $(free -h | grep Mem | awk '{print $2}')"
          echo "Available Memory: $(free -h | grep Mem | awk '{print $7}')"
          echo ""
          echo "--- Disk Usage ---"
          df -h
          echo ""
          echo "--- Runner Environment ---"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Name: ${{ runner.name }}"
          echo "Workspace: ${{ github.workspace }}"
          echo "GitHub API URL: ${{ github.api_url }}"
          echo ""
          echo "--- Network Information ---"
          echo "IP Address: $(hostname -I)"
          echo ""
          echo "--- Environment Variables ---"
          echo "PATH: $PATH"
          echo "USER: $(whoami)"
          echo "Home: $HOME"
          echo ""
          echo "--- GitHub Context ---"
          echo "Event: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."
